name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: arduino/setup-protoc@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: Install protoc-gen-go
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        echo "PATH=$PATH:$GOPATH/bin" >> $GITHUB_ENV

    - name: Generate
      run: go generate -v ./...

    - name: Build Azure
      run: go build -o _out/bart-azure -tags "azure all"

    - name: Build Azurite
      run: go build -o _out/bart-azurite -tags "azurite all"

    - name: Build Files
      run: go build -o _out/bart-files -tags "files all"
